---
  parser:
    babel-eslint

  parserOptions:
    ecmaVersion: 2015
    sourceType: "module"

  plugins:
    - node
    - flowtype

  extends:
    - eslint:recommended
    - plugin:node/recommended
    - plugin:flowtype/recommended
    - airbnb-base

  env:
    node: true

  rules:
    no-console: off
    node/no-unpublished-require: off
