service:
  name: sensors-are-down-alexa-skill

frameworkVersion: ">=1.8.0 <2.0.0"

provider:
  name: aws
  runtime: nodejs6.10

package:
  exclude:
    - audio/**
    - test/**
    - speechAssets/**
    - *.md
    - package*.json

functions:
  sensorsAreDown:
    handler: index.handler
    events:
      - alexaSkill
