# This is the appId for Will's skill deployment. It will be used by default.
# To override this, you can define a config/local.yaml file with a different app ID.
deployment:
  appId: amzn1.ask.skill.13bc8151-99af-4413-8667-a7f206562bc1
db:
  tableName: sensorsAreDownUsers
# I think cards do not make sense as "config" and should just be in separate metadata yaml file
cards:
  # cardId:
    # name: Readable name of card
    # description: Readable description of the card
    # special: card has rules in code (defaults to false)
    # strength: base strength of card (defaults to 0)
    # damageStrength: bonus strength only used damaging the opponent card (defaults to 0)
    # shieldStrength: bonus strength only used when being damaged (defaults to 0)
    # offense: card can be used on offense (defaults to false)
    # defense: card can be used on defense (defaults to false)
    # space: card is used in space (defaults to false)
    # planet: card is used on planet (defaults to false)
    # count: number of times card is can be used before card is removed from deck (defaults to 1)
  relentlessSwarm:
    name: Relentless Swarm
    description: Relentless Swarm are weak ships but we are stocked with 4 rounds of them
    strength: 2
    offense: true
    defense: true
    space: true
    count: 4
  ionTurrets:
    name: Ion Turrets
    description: Ion Turrets are tough. Hopefully they will hold
    strength: 3
    shieldStrength: 1
    defense: true
    space: true
  assaultFrigates:
    name: Assault Frigates
    description: Assault Frigates are our strongest ships for space combat
    strength: 4
    offense: true
    defense: true
    space: true
  planetaryBombers:
    name: Planetary Bombers
    description: When the planet seems lost, the Planetary Bombers will destroy everything on it
    special: 'preplaycards'
    strength: 1
    defense: true
    planet: true
  tankBattalion:
    name: Tank Battalion
    description: The Tank Battalion is consistent planet battler
    strength: 3
    offense: true
    defense: true
    planet: true
    count: 3
  groundTroops:
    name: Ground Troops
    description: Ground Troops are pretty much worthless. But we throw'em down there just to disrupt things.
    strength: 2
    damageStrength: 1
    offense: true
    defense: true
    planet: true
    count: 4
  scrapHarvesters:
    name: Scrap Harvesters
    description: Our Scrap Harvesters fly in and can upgrade themselves with scrap from a defeated enemy
    special: 'postcombat'
    strength: 3
    offense: true
    space: true
    count: 2
  nanightStorm:
    name: Nanight Storm
    description: The Nanight Storm descends on the planet like a cloud then comes back to partially re-energize before attacking again
    strength: 5
    special: 'preplaycards'
    offense: true
    defense: true
    planet: true
    count: 2
